---

- name: restart patroni-watchdog
  systemd:
    name: patroni-watchdog
    state: restarted
    daemon_reload: yes
    enabled: yes
  notify:
    - restart watchdog
  when: patroni_watchdog | bool

- name: restart watchdog
  systemd:
    name: watchdog
    state: restarted
    enabled: yes
  when: patroni_watchdog | bool

- name: restart patroni
  systemd:
    name: patroni.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart haproxy
  systemd:
    name: haproxy.service
    state: restarted
    daemon_reload: yes
    enabled: yes
